import { Layout } from "@/components";
import '../styles/globals.scss';

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body>
                <Layout children={children} />
            </body>
        </html>
    );
};
